package com.pojo;

public class AdminCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admincode.codeid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admincode.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer codenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admincode.codeid
     *
     * @return the value of admincode.codeid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admincode.codeid
     *
     * @param codeid the value for admincode.codeid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setCodeid(Integer codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admincode.codenum
     *
     * @return the value of admincode.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getCodenum() {
        return codenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admincode.codenum
     *
     * @param codenum the value for admincode.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setCodenum(Integer codenum) {
        this.codenum = codenum;
    }
}