package com.pojo;

public class Kjhm {

    private String onenum;
    private String twonum;
    private String threenum;

    public String getOnenum() {
        return onenum;
    }

    public void setOnenum(String onenum) {
        this.onenum = onenum;
    }

    public String getTwonum() {
        return twonum;
    }

    public void setTwonum(String twonum) {
        this.twonum = twonum;
    }

    public String getThreenum() {
        return threenum;
    }

    public void setThreenum(String threenum) {
        this.threenum = threenum;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kjhm.kjid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer kjid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kjhm.kjqh
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer kjqh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kjhm.kjnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String kjnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kjhm.kjid
     *
     * @return the value of kjhm.kjid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getKjid() {
        return kjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kjhm.kjid
     *
     * @param kjid the value for kjhm.kjid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setKjid(Integer kjid) {
        this.kjid = kjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kjhm.kjqh
     *
     * @return the value of kjhm.kjqh
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getKjqh() {
        return kjqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kjhm.kjqh
     *
     * @param kjqh the value for kjhm.kjqh
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setKjqh(Integer kjqh) {
        this.kjqh = kjqh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kjhm.kjnum
     *
     * @return the value of kjhm.kjnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getKjnum() {
        return kjnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kjhm.kjnum
     *
     * @param kjnum the value for kjhm.kjnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setKjnum(String kjnum) {
        this.kjnum = kjnum;
    }
}