package com.pojo;

import java.util.ArrayList;
import java.util.List;

public class KjhmExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public KjhmExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKjidIsNull() {
            addCriterion("kjid is null");
            return (Criteria) this;
        }

        public Criteria andKjidIsNotNull() {
            addCriterion("kjid is not null");
            return (Criteria) this;
        }

        public Criteria andKjidEqualTo(Integer value) {
            addCriterion("kjid =", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidNotEqualTo(Integer value) {
            addCriterion("kjid <>", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidGreaterThan(Integer value) {
            addCriterion("kjid >", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidGreaterThanOrEqualTo(Integer value) {
            addCriterion("kjid >=", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidLessThan(Integer value) {
            addCriterion("kjid <", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidLessThanOrEqualTo(Integer value) {
            addCriterion("kjid <=", value, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidIn(List<Integer> values) {
            addCriterion("kjid in", values, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidNotIn(List<Integer> values) {
            addCriterion("kjid not in", values, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidBetween(Integer value1, Integer value2) {
            addCriterion("kjid between", value1, value2, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjidNotBetween(Integer value1, Integer value2) {
            addCriterion("kjid not between", value1, value2, "kjid");
            return (Criteria) this;
        }

        public Criteria andKjqhIsNull() {
            addCriterion("kjqh is null");
            return (Criteria) this;
        }

        public Criteria andKjqhIsNotNull() {
            addCriterion("kjqh is not null");
            return (Criteria) this;
        }

        public Criteria andKjqhEqualTo(Integer value) {
            addCriterion("kjqh =", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhNotEqualTo(Integer value) {
            addCriterion("kjqh <>", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhGreaterThan(Integer value) {
            addCriterion("kjqh >", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhGreaterThanOrEqualTo(Integer value) {
            addCriterion("kjqh >=", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhLessThan(Integer value) {
            addCriterion("kjqh <", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhLessThanOrEqualTo(Integer value) {
            addCriterion("kjqh <=", value, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhIn(List<Integer> values) {
            addCriterion("kjqh in", values, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhNotIn(List<Integer> values) {
            addCriterion("kjqh not in", values, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhBetween(Integer value1, Integer value2) {
            addCriterion("kjqh between", value1, value2, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjqhNotBetween(Integer value1, Integer value2) {
            addCriterion("kjqh not between", value1, value2, "kjqh");
            return (Criteria) this;
        }

        public Criteria andKjnumIsNull() {
            addCriterion("kjnum is null");
            return (Criteria) this;
        }

        public Criteria andKjnumIsNotNull() {
            addCriterion("kjnum is not null");
            return (Criteria) this;
        }

        public Criteria andKjnumEqualTo(String value) {
            addCriterion("kjnum =", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumNotEqualTo(String value) {
            addCriterion("kjnum <>", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumGreaterThan(String value) {
            addCriterion("kjnum >", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumGreaterThanOrEqualTo(String value) {
            addCriterion("kjnum >=", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumLessThan(String value) {
            addCriterion("kjnum <", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumLessThanOrEqualTo(String value) {
            addCriterion("kjnum <=", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumLike(String value) {
            addCriterion("kjnum like", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumNotLike(String value) {
            addCriterion("kjnum not like", value, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumIn(List<String> values) {
            addCriterion("kjnum in", values, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumNotIn(List<String> values) {
            addCriterion("kjnum not in", values, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumBetween(String value1, String value2) {
            addCriterion("kjnum between", value1, value2, "kjnum");
            return (Criteria) this;
        }

        public Criteria andKjnumNotBetween(String value1, String value2) {
            addCriterion("kjnum not between", value1, value2, "kjnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kjhm
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 27 21:38:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}