package com.pojo;

public class LoginUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.username
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.passwd
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.uemail
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String uemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.invitationcode
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String invitationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column loginuser.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer codenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.userid
     *
     * @return the value of loginuser.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.userid
     *
     * @param userid the value for loginuser.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.username
     *
     * @return the value of loginuser.username
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.username
     *
     * @param username the value for loginuser.username
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.passwd
     *
     * @return the value of loginuser.passwd
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.passwd
     *
     * @param passwd the value for loginuser.passwd
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.uemail
     *
     * @return the value of loginuser.uemail
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.uemail
     *
     * @param uemail the value for loginuser.uemail
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.invitationcode
     *
     * @return the value of loginuser.invitationcode
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getInvitationcode() {
        return invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.invitationcode
     *
     * @param invitationcode the value for loginuser.invitationcode
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setInvitationcode(String invitationcode) {
        this.invitationcode = invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column loginuser.codenum
     *
     * @return the value of loginuser.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getCodenum() {
        return codenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column loginuser.codenum
     *
     * @param codenum the value for loginuser.codenum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setCodenum(Integer codenum) {
        this.codenum = codenum;
    }
}