package com.pojo;

public class Number {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number.id
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number.number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column number.peilv
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Double peilv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number.id
     *
     * @return the value of number.id
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number.id
     *
     * @param id the value for number.id
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number.number
     *
     * @return the value of number.number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number.number
     *
     * @param number the value for number.number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column number.peilv
     *
     * @return the value of number.peilv
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Double getPeilv() {
        return peilv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column number.peilv
     *
     * @param peilv the value for number.peilv
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setPeilv(Double peilv) {
        this.peilv = peilv;
    }
}