package com.pojo;

import java.util.Date;

public class Topup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.topupid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer topupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.topnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String topnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.topmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer topmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.topuserid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer topuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.toptime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Date toptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topup.topbs
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer topbs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.topupid
     *
     * @return the value of topup.topupid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getTopupid() {
        return topupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.topupid
     *
     * @param topupid the value for topup.topupid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setTopupid(Integer topupid) {
        this.topupid = topupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.topnum
     *
     * @return the value of topup.topnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getTopnum() {
        return topnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.topnum
     *
     * @param topnum the value for topup.topnum
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setTopnum(String topnum) {
        this.topnum = topnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.topmoney
     *
     * @return the value of topup.topmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getTopmoney() {
        return topmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.topmoney
     *
     * @param topmoney the value for topup.topmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setTopmoney(Integer topmoney) {
        this.topmoney = topmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.topuserid
     *
     * @return the value of topup.topuserid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getTopuserid() {
        return topuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.topuserid
     *
     * @param topuserid the value for topup.topuserid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setTopuserid(Integer topuserid) {
        this.topuserid = topuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.toptime
     *
     * @return the value of topup.toptime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Date getToptime() {
        return toptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.toptime
     *
     * @param toptime the value for topup.toptime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setToptime(Date toptime) {
        this.toptime = toptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topup.topbs
     *
     * @return the value of topup.topbs
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getTopbs() {
        return topbs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topup.topbs
     *
     * @param topbs the value for topup.topbs
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setTopbs(Integer topbs) {
        this.topbs = topbs;
    }
}