package com.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TopupExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public TopupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTopupidIsNull() {
            addCriterion("topupid is null");
            return (Criteria) this;
        }

        public Criteria andTopupidIsNotNull() {
            addCriterion("topupid is not null");
            return (Criteria) this;
        }

        public Criteria andTopupidEqualTo(Integer value) {
            addCriterion("topupid =", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidNotEqualTo(Integer value) {
            addCriterion("topupid <>", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidGreaterThan(Integer value) {
            addCriterion("topupid >", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidGreaterThanOrEqualTo(Integer value) {
            addCriterion("topupid >=", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidLessThan(Integer value) {
            addCriterion("topupid <", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidLessThanOrEqualTo(Integer value) {
            addCriterion("topupid <=", value, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidIn(List<Integer> values) {
            addCriterion("topupid in", values, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidNotIn(List<Integer> values) {
            addCriterion("topupid not in", values, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidBetween(Integer value1, Integer value2) {
            addCriterion("topupid between", value1, value2, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopupidNotBetween(Integer value1, Integer value2) {
            addCriterion("topupid not between", value1, value2, "topupid");
            return (Criteria) this;
        }

        public Criteria andTopnumIsNull() {
            addCriterion("topnum is null");
            return (Criteria) this;
        }

        public Criteria andTopnumIsNotNull() {
            addCriterion("topnum is not null");
            return (Criteria) this;
        }

        public Criteria andTopnumEqualTo(String value) {
            addCriterion("topnum =", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumNotEqualTo(String value) {
            addCriterion("topnum <>", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumGreaterThan(String value) {
            addCriterion("topnum >", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumGreaterThanOrEqualTo(String value) {
            addCriterion("topnum >=", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumLessThan(String value) {
            addCriterion("topnum <", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumLessThanOrEqualTo(String value) {
            addCriterion("topnum <=", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumLike(String value) {
            addCriterion("topnum like", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumNotLike(String value) {
            addCriterion("topnum not like", value, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumIn(List<String> values) {
            addCriterion("topnum in", values, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumNotIn(List<String> values) {
            addCriterion("topnum not in", values, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumBetween(String value1, String value2) {
            addCriterion("topnum between", value1, value2, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopnumNotBetween(String value1, String value2) {
            addCriterion("topnum not between", value1, value2, "topnum");
            return (Criteria) this;
        }

        public Criteria andTopmoneyIsNull() {
            addCriterion("topmoney is null");
            return (Criteria) this;
        }

        public Criteria andTopmoneyIsNotNull() {
            addCriterion("topmoney is not null");
            return (Criteria) this;
        }

        public Criteria andTopmoneyEqualTo(Integer value) {
            addCriterion("topmoney =", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyNotEqualTo(Integer value) {
            addCriterion("topmoney <>", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyGreaterThan(Integer value) {
            addCriterion("topmoney >", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("topmoney >=", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyLessThan(Integer value) {
            addCriterion("topmoney <", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyLessThanOrEqualTo(Integer value) {
            addCriterion("topmoney <=", value, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyIn(List<Integer> values) {
            addCriterion("topmoney in", values, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyNotIn(List<Integer> values) {
            addCriterion("topmoney not in", values, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyBetween(Integer value1, Integer value2) {
            addCriterion("topmoney between", value1, value2, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopmoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("topmoney not between", value1, value2, "topmoney");
            return (Criteria) this;
        }

        public Criteria andTopuseridIsNull() {
            addCriterion("topuserid is null");
            return (Criteria) this;
        }

        public Criteria andTopuseridIsNotNull() {
            addCriterion("topuserid is not null");
            return (Criteria) this;
        }

        public Criteria andTopuseridEqualTo(Integer value) {
            addCriterion("topuserid =", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridNotEqualTo(Integer value) {
            addCriterion("topuserid <>", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridGreaterThan(Integer value) {
            addCriterion("topuserid >", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("topuserid >=", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridLessThan(Integer value) {
            addCriterion("topuserid <", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridLessThanOrEqualTo(Integer value) {
            addCriterion("topuserid <=", value, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridIn(List<Integer> values) {
            addCriterion("topuserid in", values, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridNotIn(List<Integer> values) {
            addCriterion("topuserid not in", values, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridBetween(Integer value1, Integer value2) {
            addCriterion("topuserid between", value1, value2, "topuserid");
            return (Criteria) this;
        }

        public Criteria andTopuseridNotBetween(Integer value1, Integer value2) {
            addCriterion("topuserid not between", value1, value2, "topuserid");
            return (Criteria) this;
        }

        public Criteria andToptimeIsNull() {
            addCriterion("toptime is null");
            return (Criteria) this;
        }

        public Criteria andToptimeIsNotNull() {
            addCriterion("toptime is not null");
            return (Criteria) this;
        }

        public Criteria andToptimeEqualTo(Date value) {
            addCriterion("toptime =", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeNotEqualTo(Date value) {
            addCriterion("toptime <>", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeGreaterThan(Date value) {
            addCriterion("toptime >", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("toptime >=", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeLessThan(Date value) {
            addCriterion("toptime <", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeLessThanOrEqualTo(Date value) {
            addCriterion("toptime <=", value, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeIn(List<Date> values) {
            addCriterion("toptime in", values, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeNotIn(List<Date> values) {
            addCriterion("toptime not in", values, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeBetween(Date value1, Date value2) {
            addCriterion("toptime between", value1, value2, "toptime");
            return (Criteria) this;
        }

        public Criteria andToptimeNotBetween(Date value1, Date value2) {
            addCriterion("toptime not between", value1, value2, "toptime");
            return (Criteria) this;
        }

        public Criteria andTopbsIsNull() {
            addCriterion("topbs is null");
            return (Criteria) this;
        }

        public Criteria andTopbsIsNotNull() {
            addCriterion("topbs is not null");
            return (Criteria) this;
        }

        public Criteria andTopbsEqualTo(Integer value) {
            addCriterion("topbs =", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsNotEqualTo(Integer value) {
            addCriterion("topbs <>", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsGreaterThan(Integer value) {
            addCriterion("topbs >", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsGreaterThanOrEqualTo(Integer value) {
            addCriterion("topbs >=", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsLessThan(Integer value) {
            addCriterion("topbs <", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsLessThanOrEqualTo(Integer value) {
            addCriterion("topbs <=", value, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsIn(List<Integer> values) {
            addCriterion("topbs in", values, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsNotIn(List<Integer> values) {
            addCriterion("topbs not in", values, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsBetween(Integer value1, Integer value2) {
            addCriterion("topbs between", value1, value2, "topbs");
            return (Criteria) this;
        }

        public Criteria andTopbsNotBetween(Integer value1, Integer value2) {
            addCriterion("topbs not between", value1, value2, "topbs");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topup
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 27 21:38:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table topup
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}