package com.pojo;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userinfoid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer userinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userprevid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer userprevid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.usertype
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.registertime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.iplocation
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String iplocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.returnmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Double returnmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.headurl
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String headurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userinfoid
     *
     * @return the value of userinfo.userinfoid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUserinfoid() {
        return userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userinfoid
     *
     * @param userinfoid the value for userinfo.userinfoid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUserinfoid(Integer userinfoid) {
        this.userinfoid = userinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userprevid
     *
     * @return the value of userinfo.userprevid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUserprevid() {
        return userprevid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userprevid
     *
     * @param userprevid the value for userinfo.userprevid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUserprevid(Integer userprevid) {
        this.userprevid = userprevid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.usertype
     *
     * @return the value of userinfo.usertype
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.usertype
     *
     * @param usertype the value for userinfo.usertype
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.registertime
     *
     * @return the value of userinfo.registertime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.registertime
     *
     * @param registertime the value for userinfo.registertime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.iplocation
     *
     * @return the value of userinfo.iplocation
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getIplocation() {
        return iplocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.iplocation
     *
     * @param iplocation the value for userinfo.iplocation
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setIplocation(String iplocation) {
        this.iplocation = iplocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.money
     *
     * @return the value of userinfo.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.money
     *
     * @param money the value for userinfo.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.returnmoney
     *
     * @return the value of userinfo.returnmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Double getReturnmoney() {
        return returnmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.returnmoney
     *
     * @param returnmoney the value for userinfo.returnmoney
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setReturnmoney(Double returnmoney) {
        this.returnmoney = returnmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.headurl
     *
     * @return the value of userinfo.headurl
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.headurl
     *
     * @param headurl the value for userinfo.headurl
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl;
    }
}