package com.pojo;

import java.util.Date;

public class Xiazhu {

    private String newtime;
    public String getNewtime() {
        return newtime;
    }


    public void setNewtime(String newtime) {
        this.newtime = newtime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.xzid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer xzid;

    private double keying;

    public double getKeying() {
        return keying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.xztime
     *
     * @param keying the value for xiazhu.xztime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setKeying(double keying) {
        this.keying = keying;
    }



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.xztime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private int xztime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.issue
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer issue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.xznumber
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String xznumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.odds
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Double odds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.location
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.close
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Integer close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiazhu.fanli
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    private Double fanli;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.xzid
     *
     * @return the value of xiazhu.xzid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getXzid() {
        return xzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.xzid
     *
     * @param xzid the value for xiazhu.xzid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setXzid(Integer xzid) {
        this.xzid = xzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.userid
     *
     * @return the value of xiazhu.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.userid
     *
     * @param userid the value for xiazhu.userid
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.xztime
     *
     * @return the value of xiazhu.xztime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public int getXztime() {
        return xztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.xztime
     *
     * @param xztime the value for xiazhu.xztime
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setXztime(int xztime) {
        this.xztime = xztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.issue
     *
     * @return the value of xiazhu.issue
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getIssue() {
        return issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.issue
     *
     * @param issue the value for xiazhu.issue
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setIssue(Integer issue) {
        this.issue = issue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.xznumber
     *
     * @return the value of xiazhu.xznumber
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getXznumber() {
        return xznumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.xznumber
     *
     * @param xznumber the value for xiazhu.xznumber
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setXznumber(String xznumber) {
        this.xznumber = xznumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.odds
     *
     * @return the value of xiazhu.odds
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Double getOdds() {
        return odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.odds
     *
     * @param odds the value for xiazhu.odds
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setOdds(Double odds) {
        this.odds = odds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.location
     *
     * @return the value of xiazhu.location
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.location
     *
     * @param location the value for xiazhu.location
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.money
     *
     * @return the value of xiazhu.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.money
     *
     * @param money the value for xiazhu.money
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.close
     *
     * @return the value of xiazhu.close
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Integer getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.close
     *
     * @param close the value for xiazhu.close
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setClose(Integer close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiazhu.fanli
     *
     * @return the value of xiazhu.fanli
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public Double getFanli() {
        return fanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiazhu.fanli
     *
     * @param fanli the value for xiazhu.fanli
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    public void setFanli(Double fanli) {
        this.fanli = fanli;
    }
}