package com.dao;

import com.pojo.Kjhm;
import com.pojo.KjhmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KjhmMapper {

    List<Kjhm> selectK();

    /**
     * 新增开奖号码
     * @param kjhm
     * @return
     */
    int insertnum(Kjhm kjhm);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int countByExample(KjhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByExample(KjhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByPrimaryKey(Integer kjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insert(Kjhm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insertSelective(Kjhm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    List<Kjhm> selectByExample(KjhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    Kjhm selectByPrimaryKey(Integer kjid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Kjhm record, @Param("example") KjhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExample(@Param("record") Kjhm record, @Param("example") KjhmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKeySelective(Kjhm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kjhm
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKey(Kjhm record);
}