package com.dao;

import com.pojo.AdminCode;
import com.pojo.LoginUser;
import com.pojo.LoginUserExample;
import java.util.List;

import com.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

public interface LoginUserMapper {

    /**
     * 登录
     * @param loginuser
     * @return
     */
    LoginUser login(LoginUser loginuser);


    /**
     * 注册时判断用户名是否存在
     * @param username
     * @return
     */
    LoginUser selectName(String username);




    /**
     * 查询邀请码的类型
     * @param code
     * @return
     */
    LoginUser selectCode(String code);

    /**
     * 新增登录表的信息
     * @param loginUser
     * @return
     */
    int registerLogin(LoginUser loginUser);

    /**
     * 查询新增用户的id
     * @param username
     * @return
     */
    int selectid(String username);

    /**
     * 修改用户邀请码的使用次数
     * @param code
     * @return
     */
    int update(String code);

    /**
     * 忘记账号用邮箱找回
     * @param email
     * @return
     */
    LoginUser forgetA(String email);

    /**
     * 修改密码
     * @param passwd
     * @param email
     * @return
     */
    int updatepd(String passwd,String email);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    LoginUser selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginuser
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKey(LoginUser record);
}