package com.dao;

import com.pojo.Number;
import com.pojo.NumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NumberMapper {

    /**
     * 查询开奖号码
     * @return
     */
    List<Number> selectNum();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int countByExample(NumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByExample(NumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insert(Number record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insertSelective(Number record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    List<Number> selectByExample(NumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    Number selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Number record, @Param("example") NumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExample(@Param("record") Number record, @Param("example") NumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKeySelective(Number record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table number
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKey(Number record);
}