package com.dao;

import com.pojo.UserInfo;
import com.pojo.Xiazhu;
import com.pojo.XiazhuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XiazhuMapper {

    //查询未结算注单
    List<Xiazhu> selectW(int id);
    //查询今日已结算注单
    List<Xiazhu> selectY(Xiazhu xiazhu);

    int instertxz(Xiazhu xiazhu);

    //更改下注表的状态
    int updatetype(Xiazhu xiazhu);
    //查询本期下注的用户
    List<Xiazhu> xzlist(Xiazhu xiazhu);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int countByExample(XiazhuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByExample(XiazhuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int deleteByPrimaryKey(Integer xzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insert(Xiazhu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int insertSelective(Xiazhu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    List<Xiazhu> selectByExample(XiazhuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    Xiazhu selectByPrimaryKey(Integer xzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") Xiazhu record, @Param("example") XiazhuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByExample(@Param("record") Xiazhu record, @Param("example") XiazhuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKeySelective(Xiazhu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiazhu
     *
     * @mbggenerated Wed Jun 27 21:38:33 CST 2018
     */
    int updateByPrimaryKey(Xiazhu record);
}